

mysql.url=jdbc:mysql://mysql:3306/Ticker_app
mysql.user=root
mysql.password=Kritter@1

postgresql.url=jdbc:postgresql://postgres:5432/Ticker_app
postgresql.user=postgres
postgresql.password=postgres123